# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'JunPhotoBrowse' do
  use_frameworks!

pod 'Alamofire'
pod 'Kingfisher'
pod 'SVProgressHUD'
pod 'MJRefresh'

end
